package nl.solevision.svscan.status;

public enum XSOL_TASK_STATUS {

    XSOL_EXIT_FATAL_ERROR,
    XSOL_EXIT_NO_ARGUMENTS,
    XSOL_EXIT_INVALID_ARGUMENTS,
    XSOL_TASK_STATUS_SERVER_BUSY,
    XSOL_TASK_STATUS_START_OLD_SERVER_RUNNING,
    XSOL_TASK_STATUS_START_NO_SERVER_RUNNING,
    XSOL_TASK_STATUS_START_LOCK_PIN,
    XSOL_TASK_STATUS_START_NO_FOUND_CONTROL_BOARD_AND_CAMERAS,
    XSOL_TASK_STATUS_START_NO_FOUND_CONTROL_BOARD,
    XSOL_TASK_STATUS_START_NO_FOUND_CAMERAS,
    POD_TASK_STATUS_START_FINISHED,
    XSOL_TASK_STATUS_SCAN_REQUEST,
    XSOL_TASK_STATUS_SCAN_FAILED,
    XSOL_TASK_STATUS_SCAN_FRAME_DROP,
    XSOL_TASK_STATUS_SCAN_FINISHED,
    XSOL_TASK_STATUS_SAVE_REQUEST,
    XSOL_TASK_STATUS_SAVE_PATH_NOT_EXIST,
    XSOL_TASK_STATUS_SAVE_NO_DATA,
    XSOL_TASK_STATUS_SAVE_FINISHED,
    XSOL_TASK_STATUS_EXIT_REQUEST,
    XSOL_TASK_STATUS_EXIT_RESPONSE,
    XSOL_TASK_STATUS_MACHINE_REQUEST,
    XSOL_TASK_STATUS_HEEL_TOE_LASER_REQUEST,
    XSOL_TASK_STATUS_HEEL_TOE_LASER_ON,
    XSOL_TASK_STATUS_HEEL_TOE_LASER_OFF

}
