package nl.solevision.svscan.enums;

public enum XsolTaskStatus {

    XSOL_EXIT_FATAL_ERROR(0),
    XSOL_EXIT_NO_ARGUMENTS(1),
    XSOL_EXIT_INVALID_ARGUMENTS(2),
    XSOL_TASK_STATUS_SERVER_BUSY(3),
    XSOL_TASK_STATUS_START_OLD_SERVER_RUNNING(4),
    XSOL_TASK_STATUS_START_NO_SERVER_RUNNING(5),
    XSOL_TASK_STATUS_START_LOCK_PIN(6),
    XSOL_TASK_STATUS_START_NO_FOUND_CONTROL_BOARD_AND_CAMERAS(7),
    XSOL_TASK_STATUS_START_NO_FOUND_CONTROL_BOARD(8),
    XSOL_TASK_STATUS_START_NO_FOUND_CAMERAS(9),
    POD_TASK_STATUS_START_FINISHED(10),
    XSOL_TASK_STATUS_SCAN_REQUEST(11),
    XSOL_TASK_STATUS_SCAN_FAILED(12),
    XSOL_TASK_STATUS_SCAN_FRAME_DROP(13),
    XSOL_TASK_STATUS_SCAN_FINISHED(14),
    XSOL_TASK_STATUS_SAVE_REQUEST(15),
    XSOL_TASK_STATUS_SAVE_PATH_NOT_EXIST(16),
    XSOL_TASK_STATUS_SAVE_NO_DATA(17),
    XSOL_TASK_STATUS_SAVE_FINISHED(18),
    XSOL_TASK_STATUS_EXIT_REQUEST(19),
    XSOL_TASK_STATUS_EXIT_RESPONSE(20),
    XSOL_TASK_STATUS_MACHINE_REQUEST(21),
    XSOL_TASK_STATUS_HEEL_TOE_LASER_REQUEST(22),
    XSOL_TASK_STATUS_HEEL_TOE_LASER_ON(23),
    XSOL_TASK_STATUS_HEEL_TOE_LASER_OFF(24);

    private final int value;

    XsolTaskStatus(int value) {
        this.value = value;
    }

    public int getValue() {
        return value;
    }
}
